

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData V1.1                                  /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

  $data.Entity.extend('MyApp.DataService.AttachmentsItem', {
    'EntitySet': { 'key':true,'type':'Edm.String','nullable':false,'required':true },
    'ItemId': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' }
  });
  
  $data.Entity.extend('MyApp.DataService.ComposedLooksItem', {
    'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
    'ContentTypeID': { 'type':'Edm.String','nullable':true },
    'ContentType': { 'type':'Edm.String','nullable':true },
    'Title': { 'type':'Edm.String','nullable':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
    'Modified': { 'type':'Edm.DateTime','nullable':true,'$FC_TargetPath':'SyndicationUpdated','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
    'Created': { 'type':'Edm.DateTime','nullable':true },
    'CreatedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'CreatedById': { 'type':'Edm.Int32','nullable':true },
    'ModifiedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'ModifiedById': { 'type':'Edm.Int32','nullable':true },
    'Owshiddenversion': { 'type':'Edm.Int32','nullable':true,'concurrencyMode':$data.ConcurrencyMode.Fixed },
    'Version': { 'type':'Edm.String','nullable':true },
    'Attachments': { 'type':'Array','elementType':'MyApp.DataService.AttachmentsItem','inverseProperty':'$$unbound' },
    'Path': { 'type':'Edm.String','nullable':true },
    'Name': { 'type':'Edm.String','nullable':true },
    'MasterPageURL': { 'type':'Edm.String','nullable':true },
    'ThemeURL': { 'type':'Edm.String','nullable':true },
    'ImageURL': { 'type':'Edm.String','nullable':true },
    'FontSchemeURL': { 'type':'Edm.String','nullable':true },
    'DisplayOrder': { 'type':'Edm.Double','nullable':true }
  });
  
  $data.Entity.extend('MyApp.DataService.MasterPageGalleryItem', {
    'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
    'ContentTypeID': { 'type':'Edm.String','nullable':true },
    'ContentType': { 'type':'Edm.String','nullable':true },
    'Created': { 'type':'Edm.DateTime','nullable':true },
    'CreatedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'CreatedById': { 'type':'Edm.Int32','nullable':true },
    'Modified': { 'type':'Edm.DateTime','nullable':true,'$FC_TargetPath':'SyndicationUpdated','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
    'ModifiedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'ModifiedById': { 'type':'Edm.Int32','nullable':true },
    'CopySource': { 'type':'Edm.String','nullable':true },
    'ApprovalStatus': { 'type':'Edm.String','nullable':true },
    'Path': { 'type':'Edm.String','nullable':true },
    'CheckedOutTo': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'CheckedOutToId': { 'type':'Edm.Int32','nullable':true },
    'Name': { 'type':'Edm.String','nullable':true },
    'VirusStatus': { 'type':'Edm.String','nullable':true },
    'IsCurrentVersion': { 'type':'Edm.Boolean','nullable':true },
    'Owshiddenversion': { 'type':'Edm.Int32','nullable':true,'concurrencyMode':$data.ConcurrencyMode.Fixed },
    'Version': { 'type':'Edm.String','nullable':true },
    'Description': { 'type':'Edm.String','nullable':true },
    'CompatibleUIVersionS': { 'type':'Array','elementType':'MyApp.DataService.MasterPageGalleryCompatibleUIVersionSValue','inverseProperty':'$$unbound' },
    'DefaultCSSFile': { 'type':'Edm.String','nullable':true },
    'Hidden': { 'type':'Edm.Boolean','nullable':true },
    'TargetControlType': { 'type':'MyApp.DataService.MasterPageGalleryTargetControlTypeValue','inverseProperty':'$$unbound' },
    'TargetControlTypeValue': { 'type':'Edm.String','nullable':true },
    'Icon': { 'type':'Edm.String','nullable':true },
    'Standalone': { 'type':'MyApp.DataService.MasterPageGalleryStandaloneValue','inverseProperty':'$$unbound' },
    'StandaloneValue': { 'type':'Edm.String','nullable':true },
    'TargetScope': { 'type':'Edm.String','nullable':true },
    'TargetListTemplateID': { 'type':'Edm.String','nullable':true }
  });
  
  $data.Entity.extend('MyApp.DataService.MasterPageGalleryCompatibleUIVersionSValue', {
    'Value': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' }
  });
  
  $data.Entity.extend('MyApp.DataService.MasterPageGalleryStandaloneValue', {
    'Value': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' }
  });
  
  $data.Entity.extend('MyApp.DataService.MasterPageGalleryTargetControlTypeValue', {
    'Value': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' }
  });
  
  $data.Entity.extend('MyApp.DataService.ProjectsItem', {
    'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
    'ContentTypeID': { 'type':'Edm.String','nullable':true },
    'ContentType': { 'type':'Edm.String','nullable':true },
    'Title': { 'type':'Edm.String','nullable':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
    'Modified': { 'type':'Edm.DateTime','nullable':true,'$FC_TargetPath':'SyndicationUpdated','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
    'Created': { 'type':'Edm.DateTime','nullable':true },
    'CreatedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'CreatedById': { 'type':'Edm.Int32','nullable':true },
    'ModifiedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'ModifiedById': { 'type':'Edm.Int32','nullable':true },
    'Owshiddenversion': { 'type':'Edm.Int32','nullable':true,'concurrencyMode':$data.ConcurrencyMode.Fixed },
    'Version': { 'type':'Edm.String','nullable':true },
    'Attachments': { 'type':'Array','elementType':'MyApp.DataService.AttachmentsItem','inverseProperty':'$$unbound' },
    'Path': { 'type':'Edm.String','nullable':true }
  });
  
  $data.Entity.extend('MyApp.DataService.TimeTrackingListItem', {
    'ContentTypeID': { 'type':'Edm.String','nullable':true },
    'Title': { 'type':'Edm.String','nullable':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
    'Employee': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'EmployeeId': { 'type':'Edm.Int32','nullable':true },
    'ProjectTask': { 'type':'MyApp.DataService.ProjectsItem','inverseProperty':'$$unbound' },
    'ProjectTaskId': { 'type':'Edm.Int32','nullable':true },
    'DurationHours': { 'type':'Edm.Double','nullable':true },
    'Date': { 'type':'Edm.DateTime','nullable':true },
    'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
    'ContentType': { 'type':'Edm.String','nullable':true },
    'Modified': { 'type':'Edm.DateTime','nullable':true,'$FC_TargetPath':'SyndicationUpdated','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
    'Created': { 'type':'Edm.DateTime','nullable':true },
    'CreatedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'CreatedById': { 'type':'Edm.Int32','nullable':true },
    'ModifiedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'ModifiedById': { 'type':'Edm.Int32','nullable':true },
    'Owshiddenversion': { 'type':'Edm.Int32','nullable':true,'concurrencyMode':$data.ConcurrencyMode.Fixed },
    'Version': { 'type':'Edm.String','nullable':true },
    'Attachments': { 'type':'Array','elementType':'MyApp.DataService.AttachmentsItem','inverseProperty':'$$unbound' },
    'Path': { 'type':'Edm.String','nullable':true }
  });
  
  $data.Entity.extend('MyApp.DataService.UserInformationListItem', {
    'ContentTypeID': { 'type':'Edm.String','nullable':true },
    'Name': { 'type':'Edm.String','nullable':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
    'Account': { 'type':'Edm.String','nullable':true },
    'WorkEmail': { 'type':'Edm.String','nullable':true },
    'MobilePhone': { 'type':'Edm.String','nullable':true },
    'AboutMe': { 'type':'Edm.String','nullable':true },
    'SIPAddress': { 'type':'Edm.String','nullable':true },
    'IsSiteAdmin': { 'type':'Edm.Boolean','nullable':true },
    'Deleted': { 'type':'Edm.Boolean','nullable':true },
    'Hidden': { 'type':'Edm.Boolean','nullable':true },
    'Picture': { 'type':'Edm.String','nullable':true },
    'Department': { 'type':'Edm.String','nullable':true },
    'Title': { 'type':'Edm.String','nullable':true },
    'FirstName': { 'type':'Edm.String','nullable':true },
    'LastName': { 'type':'Edm.String','nullable':true },
    'WorkPhone': { 'type':'Edm.String','nullable':true },
    'UserName': { 'type':'Edm.String','nullable':true },
    'WebSite': { 'type':'Edm.String','nullable':true },
    'AskMeAbout': { 'type':'Edm.String','nullable':true },
    'Office': { 'type':'Edm.String','nullable':true },
    'Id': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
    'ContentType': { 'type':'Edm.String','nullable':true },
    'Modified': { 'type':'Edm.DateTime','nullable':true,'$FC_TargetPath':'SyndicationUpdated','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
    'Created': { 'type':'Edm.DateTime','nullable':true },
    'CreatedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'CreatedById': { 'type':'Edm.Int32','nullable':true },
    'ModifiedBy': { 'type':'MyApp.DataService.UserInformationListItem','inverseProperty':'$$unbound' },
    'ModifiedById': { 'type':'Edm.Int32','nullable':true },
    'Owshiddenversion': { 'type':'Edm.Int32','nullable':true,'concurrencyMode':$data.ConcurrencyMode.Fixed },
    'Version': { 'type':'Edm.String','nullable':true },
    'Attachments': { 'type':'Array','elementType':'MyApp.DataService.AttachmentsItem','inverseProperty':'$$unbound' },
    'Path': { 'type':'Edm.String','nullable':true }
  });
  
  $data.EntityContext.extend('MyApp.DataService.Context', {
    'Attachments': { type: $data.EntitySet, elementType: MyApp.DataService.AttachmentsItem },
    'ComposedLooks': { type: $data.EntitySet, elementType: MyApp.DataService.ComposedLooksItem },
    'MasterPageGallery': { type: $data.EntitySet, elementType: MyApp.DataService.MasterPageGalleryItem },
    'MasterPageGalleryCompatibleUIVersionS': { type: $data.EntitySet, elementType: MyApp.DataService.MasterPageGalleryCompatibleUIVersionSValue },
    'MasterPageGalleryStandalone': { type: $data.EntitySet, elementType: MyApp.DataService.MasterPageGalleryStandaloneValue },
    'MasterPageGalleryTargetControlType': { type: $data.EntitySet, elementType: MyApp.DataService.MasterPageGalleryTargetControlTypeValue },
    'Projects': { type: $data.EntitySet, elementType: MyApp.DataService.ProjectsItem },
    'TimeTrackingList': { type: $data.EntitySet, elementType: MyApp.DataService.TimeTrackingListItem },
    'UserInformationList': { type: $data.EntitySet, elementType: MyApp.DataService.UserInformationListItem },
    'ConvertListTitleToEntitySetName': $data.EntityContext.generateServiceOperation({ serviceName:'ConvertListTitleToEntitySetName', returnType:  'Edm.String' , params: [{ listTitle: 'Edm.String' }], method: 'GET' })
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(MyApp.DataService.Context);
  
      
})(window, $data);
      
    